name = "la_image_notebooks"
uuid = "8e0fbc1a-4e12-4c0b-9c3c-0a4caa3f6c2a"

[deps]
AbstractAlgebra = "c3fe647b"
BlockArrays = "8e7c35d0"
GenericLinearAlgebra = "14197337"
Hadamard = "4a05ff16"
RowEchelon = "af85af4c"
Latexify = "23fbe1c1"
LaTeXStrings = "b964fa9f"
QuadGK = "1fd47b50"
IOCapture = "b5f81e59"
FFTW = "7a1cc6ca"
DSP = "717857b8"
ToeplitzMatrices = "c751599d"
Polynomials = "f27b6e38"
Colors = "5ae59095"
Plots = "91a5bcdd"
Interact = "c601a237"
SymPy = "24249f21"
Distributions = "31c24e10"
Images = "916415d5"
TestImages = "5e47fb64"
NearestNeighbors = "b8a86587"
MosaicViews = "e94cdb99"
PrettyTables = "08abe8d2"
Revise = "295af30f"
CSV = "336ed68f"
DataFrames = "a93c6f00"
RDatasets = "ce6b1742"
StatsBase = "2913bbd2"
StatsPlots = "f3b207a7"
PlotlyJS = "f0f68f2c"
PythonCall = "6099a3de"
PyCall = "438e738f"
Gtk4 = "478199e0"
ImageView = "86fae568"
IJulia = "7073ff75"

