image: docker:27.5.1-cli

services:
  - name: docker:27.5.1-dind
    command: ["--tls=false"]

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: "1"
  BUILDX_GIT_INFO: "false"

stages:
  - validate

ela-course:
  stage: validate
  timeout: 3 hours
  before_script:
    - apk add --no-cache bash make python3
    - docker info
    - docker buildx version
  script:
    - make check_notebook_api
    - make check_deps_lock
    - make l_ci_la_course IMAGE_LA_COURSE=la-course-ci
    - make check_integration_smoke_docker NOTEBOOK_CHECK_IMAGE=la-course-ci:1.0
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
