#!/bin/sh
latexmk -xelatex    $1.tex && \
latexmk -xelatex -c $1.tex && \
dvisvgm --font-format=woff2 --zoom=1 --exact $1.xdv $1.svg
#latexmk -xelatex $1.tex && \
#latexmk -xelatex -c $1.tex && \
#pdf2svg $1.pdf /tmp/temp_$1.svg && \
#inkscape --export-plain-svg -D --export-margin=1 -o $1.svg /tmp/temp_$1.svg

