ARG BASE_IMAGE=ea42gh/julia-python-jupyter:0.1
FROM ${BASE_IMAGE}

ENV JULIA_CONDAPKG_BACKEND=Null
ENV JULIA_PYTHONCALL_EXE=/usr/local/bin/python3
ENV JULIA_PROJECT=/home/jovyan/.julia_env
ENV JULIACALL_PROJECT=/home/jovyan/.julia_env
ENV PYTHON_JULIACALL_EXE=/usr/local/julia/bin/julia
ENV PYTHON_JULIACALL_PROJECT=/home/jovyan/.julia_env
ENV PYJULIAPKG_PROJECT=/home/jovyan/.julia_env
ENV JULIAPKG_PROJECT=/home/jovyan/.julia_env
ENV JULIA_PKG_PRECOMPILE_AUTO=0

USER root
WORKDIR /tmp

RUN mkdir -p /opt/ea42gh \
 && chown jovyan:jovyan /opt/ea42gh
COPY binder/docs/README.md /opt/ea42gh/docs/README.md

RUN apt-get update && apt-get install -y --no-install-recommends --fix-missing \
    graphviz-dev \
    ffmpeg \
    libcairo2-dev \
    libpango1.0-dev \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

# Install Julia packages early for better layer caching.
COPY binder/install_julia_packages.jl /tmp/install_julia_packages.jl
RUN mkdir -p /home/jovyan/.julia /home/jovyan/.julia_env \
 && chown -R jovyan:jovyan /home/jovyan/.julia /home/jovyan/.julia_env

USER jovyan

# Run package install with network registry (override offline settings for this step).
RUN JULIA_PKG_OFFLINE=false JULIA_PKG_SERVER=https://pkg.julialang.org \
    julia --startup-file=no /tmp/install_julia_packages.jl
RUN julia -e 'using Pkg; Pkg.Registry.add("General")'

USER root
RUN /usr/local/bin/python3 -m pip install --no-cache-dir \
    "mkdocs-jupyter==0.24.8" \
    "nbconvert==7.16.6"
RUN /usr/local/bin/python3 -m pip install --no-cache-dir jupyter-server-proxy
RUN /usr/local/bin/python3 -m pip install --no-cache-dir "notebook<7" nbclassic
RUN /usr/local/bin/python3 -m pip install --no-cache-dir vsapy

COPY binder/start-pluto /usr/local/bin/start-pluto
RUN chmod 0755 /usr/local/bin/start-pluto

COPY binder/jupyter_server_config.py /etc/jupyter/jupyter_server_config.py

COPY binder/install_python_libraries.py /tmp/install_python_libraries.py
RUN /usr/local/bin/python3 /tmp/install_python_libraries.py
WORKDIR /opt/ea42gh

ARG GENLAPROBLEMS_REF=main
ARG MATRIXLAYOUT_REF=main
ARG LAFIGURES_REF=master

RUN git clone --branch ${MATRIXLAYOUT_REF} --single-branch https://github.com/ea42gh/matrixlayout.git
RUN git clone --branch ${LAFIGURES_REF} --single-branch https://github.com/ea42gh/la_figures.git
RUN git clone https://github.com/ea42gh/GenLAProblems.git \
 && cd /opt/ea42gh/GenLAProblems \
 && git checkout ${GENLAPROBLEMS_REF}
RUN if grep -q '__precompile__(false)' /opt/ea42gh/GenLAProblems/src/GenLAProblems.jl; then \
      sed -i 's/__precompile__(false)/# __precompile__(false) disabled in image build experiment/' /opt/ea42gh/GenLAProblems/src/GenLAProblems.jl; \
    fi
RUN julia -e 'using Pkg; \
Pkg.activate("/opt/ea42gh/GenLAProblems"); \
Pkg.develop(path="/opt/ea42gh/LAlatex"); \
Pkg.add(Pkg.PackageSpec(url="https://github.com/Nemocas/AbstractAlgebra.jl.git", rev="v0.48.2")); \
Pkg.add("PythonCall"); \
Pkg.resolve(); \
Pkg.instantiate()'

USER root
RUN /usr/local/bin/python3 -m pip install --no-cache-dir -e /opt/ea42gh/matrixlayout
RUN /usr/local/bin/python3 -m pip install --no-cache-dir -e /opt/ea42gh/la_figures
USER jovyan

RUN mkdir -p /home/jovyan/.julia/prefs \
 && printf '%s\n' \
    'python_executable = "/usr/local/bin/python3"' \
    'conda_backend = "Null"' \
    > /home/jovyan/.julia/prefs/PythonCall.toml

RUN julia -e 'using PythonCall; pyimport("la_figures"); pyimport("matrixlayout"); println("PythonCall la_figures/matrixlayout OK")'

RUN /usr/local/bin/python3 -m mkdocs build \
    -f /opt/ea42gh/matrixlayout/mkdocs.yml \
    -d /opt/ea42gh/docs/matrixlayout
RUN mkdir -p /opt/ea42gh/docs/matrixlayout/notebooks \
 && cp -r /opt/ea42gh/matrixlayout/docs/notebooks/. /opt/ea42gh/docs/matrixlayout/notebooks/
RUN /usr/local/bin/python3 -m mkdocs build \
    -f /opt/ea42gh/la_figures/mkdocs.yml \
    -d /opt/ea42gh/docs/la_figures
RUN mkdir -p /opt/ea42gh/docs/la_figures/notebooks \
 && cp -r /opt/ea42gh/la_figures/docs/notebooks/. /opt/ea42gh/docs/la_figures/notebooks/

# Precompile LAlatex in an isolated temp env so GUI deps in JULIA_PROJECT
# (e.g. Makie) do not get pulled into this warmup step.
RUN julia -e 'using Pkg; \
Pkg.activate(; temp=true); \
Pkg.develop(path="/opt/ea42gh/LAlatex"); \
Pkg.instantiate(); \
Pkg.precompile(["LAlatex"])'
RUN PYTHONPYCACHEPREFIX=/tmp/pycache /usr/local/bin/python3 -m compileall -q \
    /opt/ea42gh/jupyter-tikz \
    /opt/ea42gh/la_figures \
    /opt/ea42gh/matrixlayout

RUN rm -rf /home/jovyan/.julia/compiled
RUN julia -e 'using Pkg; \
Pkg.activate(ENV["JULIA_PROJECT"]); \
Pkg.develop(path="/opt/ea42gh/GenLAProblems"); \
Pkg.resolve(); \
Pkg.instantiate(); \
blocked_pkgs = isfile("/home/jovyan/.julia_env_blocked_pkgs.txt") ? Set(filter(!isempty, readlines("/home/jovyan/.julia_env_blocked_pkgs.txt"))) : Set{String}(); \
pkgs = [Pkg.PackageSpec(name=name) for (name, _) in Pkg.project().dependencies if !(name in blocked_pkgs)]; \
Pkg.precompile(pkgs; strict=false)'
RUN julia -e 'using Pkg; \
Pkg.activate(ENV["JULIA_PROJECT"]); \
using GenLAProblems, LinearAlgebra, BlockArrays, RowEchelon, LaTeXStrings, Latexify, Random; \
using PythonCall, IJulia, WebIO, DataFrames, Symbolics, AbstractAlgebra; \
pyimport("la_figures"); \
pyimport("matrixlayout"); \
A, X, B = gen_gj_pb(3, 3, 3); \
A = Rational{Int}.(A); \
B = Rational{Int}.(B); \
pb = ShowGE{Rational{Int}}(A, B); \
ref!(pb; gj=true); \
GenLAProblems.rref_matrix(4, 6, 3); \
A_qr = gen_qr_problem_3(); \
W = gram_schmidt_w(A_qr); \
normalize_columns(W); \
latexify(A); \
rand(3, 3); \
df = DataFrame(a=1:3, b=4:6); \
latexify(df); \
@variables x; \
expand((x + 1)^2); \
println("Julia warmup complete")'
RUN julia -e 'using Pkg; Pkg.activate(ENV["JULIA_PROJECT"]); using GenLAProblems; \
A, X, B = gen_gj_pb(3, 3, 3); \
A = Rational{Int}.(A); \
B = Rational{Int}.(B); \
pb = ShowGE{Rational{Int}}(A, B); \
ref!(pb; gj=true); \
GenLAProblems.rref_matrix(4, 6, 3); \
A_qr = gen_qr_problem_3(); \
W = gram_schmidt_w(A_qr); \
normalize_columns(W)'
RUN julia -e 'using Pkg; \
Pkg.activate(ENV["JULIA_PROJECT"]); \
using GenLAProblems, Symbolics; \
using LinearAlgebra, RowEchelon, LaTeXStrings, BlockArrays, Latexify, PythonCall; \
@variables α[1:6], x[1:6]; \
A = [1 -2 -1 1; -1 2 3 -1; 1 0 1 -3; -1 0 1 -1]; \
h, mats = nM.gram_schmidt_qr(A; fig_scale=1.2); \
qr = qr_matrices_from_grid(mats); \
Q = qr["Q"]; \
R = qr["R"]; \
s = string(l_show(L"A = Q R = ", Q, R)); \
isempty(s) && error("l_show returned empty output for Python-backed QR matrices"); \
println("QR/l_show regression check OK")'
RUN mkdir -p /opt/ea42gh/docs/GenLAProblems \
 && if [ -d /opt/ea42gh/GenLAProblems/docs/src ]; then \
      cp -r /opt/ea42gh/GenLAProblems/docs/src/. /opt/ea42gh/docs/GenLAProblems/; \
    else \
      cp -r /opt/ea42gh/GenLAProblems/docs/. /opt/ea42gh/docs/GenLAProblems/; \
    fi
RUN mkdir -p /opt/ea42gh/docs/GenLAProblems/notebooks \
 && if [ -d /opt/ea42gh/GenLAProblems/docs/notebooks ]; then \
      cp -r /opt/ea42gh/GenLAProblems/docs/notebooks/. /opt/ea42gh/docs/GenLAProblems/notebooks/; \
    elif [ -d /opt/ea42gh/GenLAProblems/docs/src/notebooks ]; then \
      cp -r /opt/ea42gh/GenLAProblems/docs/src/notebooks/. /opt/ea42gh/docs/GenLAProblems/notebooks/; \
    fi

RUN mkdir -p /opt/ea42gh/docs/LAlatex/notebooks \
 && cp -r /opt/ea42gh/LAlatex/docs/src/notebooks/. /opt/ea42gh/docs/LAlatex/notebooks/
RUN find /opt/ea42gh/docs -name "*.ipynb" -print0 | xargs -0 jupyter trust

USER root
RUN chown -R jovyan:jovyan /home/jovyan/.julia
RUN rm -rf /tmp/*
USER jovyan


USER root
RUN mkdir -p /home/jovyan/.local/bin
COPY binder/inkscape /home/jovyan/.local/bin/inkscape
RUN chown jovyan:jovyan /home/jovyan/.local/bin/inkscape \
 && chmod 0755 /home/jovyan/.local/bin/inkscape

RUN rm -rf /tmp/* /var/tmp/*

USER jovyan
WORKDIR /home/jovyan

RUN git clone https://gitlab.com/ea42gh/elementary-linear-algebra.git
RUN chmod 0755 /home/jovyan/elementary-linear-algebra/bin/*
RUN ln -s /tmp /home/jovyan/tmp \
 && mkdir /home/jovyan/work

EXPOSE 8888 1234

#CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--ServerApp.token=", "--ServerApp.password=", "--notebook-dir=/home/jovyan", "linear-algebra-notebooks/notebooks/Index.ipynb"]
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--ServerApp.token=", "--ServerApp.password=", "--notebook-dir=/home/jovyan"]
