#!/usr/bin/env bash
# /usr/local/bin/inkscape-quiet

set -o pipefail

/usr/bin/inkscape "$@" \
  2> >(grep -v -E \
        'Failed to wrap object of type .*PangoFT2FontMap|Failed to wrap object of type .*GtkRecentManager' \
        >&2)

